errors: * npm ERR! JSON.parse Unexpected token "}" (0x7D) in JSON at position 617 while parsing near "...t.io\": \"^4.6.1\",\r\n  }\r\n}" * D:\Projects\app-service\app.js:10     origin: socket_config.CORS,             ^
ReferenceError: Cannot access 'socket_config' before initialization
    at Object.<anonymous> (D:\Projects\app-service\app.js:10:13)
* D:\Projects\app-service\app.js:8
require('./utils').LOAD_CONFIG()
                   ^

TypeError: require(...).LOAD_CONFIG is not a function
    at Object.<anonymous> (D:\Projects\app-service\app.js:8:20)
* node:internal/modules/cjs/loader:998
  throw err;
  ^

Error: Cannot find module 'socket.io-client'
Require stack:
- D:\Projects\app-service\app.js

* D:\Projects\app-service\controllers\app.controllers.js:5
const { app } = require("../models").{ { cookiecutter.app } }_models;
                                     ^

SyntaxError: Unexpected token '{'